version: '3.9'
services:
  postgres:
    image: postgres
    container_name: google_forms_clone_db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: google_forms_clone_web
    command: ./web_entrypoint.sh
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - postgres
      - redis
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 1337:443
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./cert/:/etc/nginx/cert
    depends_on:
      - web


volumes:
  postgresdata:
  media:
  static:
  
  